name: Rust Test, Build and Push to debug-binaries

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  PROJECT: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            release: '${{ env.PROJECT }}-linux'
            build: '${{ env.PROJECT }}'
          - os: macos-latest
            release: '${{ env.PROJECT }}-mac'
            build: '${{ env.PROJECT }}'
          - os: windows-latest
            release: '${{ env.PROJECT }}-win.exe'
            build: '${{ env.PROJECT }}.exe'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run Tests
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Copy Binary to ..
      shell: bash
      run: |
        cp target/debug/${{ matrix.build }} ../${{ matrix.release }}

    - name: Checkout debug-binaries branch
      uses: actions/checkout@v3
      with:
        ref: debug-binaries

    - name: Push binary to debug-binaries branch
      shell: bash
      run: |
        cp ../${{ matrix.release }} .
        chmod a+x ${{ matrix.release }}
        git add ${{ matrix.release }}
        git commit --amend -m "Debug Binaries for {{ github.sha }}"
        git push -f
