name: Rust Test, Build and Push to Debug-Dinaries

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            release: '${{ github.event.repository.name }}-linux'
            build: '${{ github.event.repository.name }}'
          - os: macos-latest
            release: '${{ github.event.repository.name }}-mac'
            build: '${{ github.event.repository.name }}'
          - os: windows-latest
            release: '${{ github.event.repository.name }}-win.exe'
            build: '${{ github.event.repository.name }}.exe'

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run Tests
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Build Release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

   - name: Save Binary for Checkout
     shell: bash
     run: |
       mv target/release/${{ matrix.build }} ../${{ matrix.release }}

    - name: Checkout Debug-Binaries
      uses: actions/checkout@v3
      with:
        ref: debug-binaries

    - name: Push Binary to Debug-Binaries
      shell: bash
      run: |
        mv ../${{ matrix.release }} .
        chmod a+x ${{ matrix.release }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{ matrix.release }}
        git commit --amend -m "Debug Binaries for ${{ github.sha }}"
        git push -f
